Fixup the previous commit for GCC. [skip ci]
Apparently, it does not like pragmas in the middle of a statement:

./missing/getopt_long.c: In function 'getopt_internal':
./missing/getopt_long.c:572:3: error: 'else' without a previous 'if'

(cherry picked from commit 34fd411f222dd93868ae677dbe8ae82d09f9f199)